### ISSUE TITLE
Failed to update on *nix system

### ISSUE THREAD

**Issue by fxdsu** [Flectone/FlectoneMix#1]
Unable to access jarfile due to extra space in filename
![image](https://github.com/Flectone/FlectoneMix/assets/137376193/2cb57364-5b95-48ac-94b3-0a3938170891)

issue source
https://github.com/Flectone/FlectoneMix/blob/9b019f2460abffeb48c47165e004a0a34032c277/src/main/java/net/flectone/system/Installation.java#L308

**Comment by TheFaser** [comment]
[fixed](https://github.com/Flectone/FlectoneMix/commit/163445955b16321d469e90fee3deb74b9d2e0f94)
